# Generated by Django 5.1.5 on 2025-01-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
